dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  looplus_core:
    git:
      ref: v1.6.2
      url: https://github.com/certainlyWrong/looplus_core.git
description: A new Flutter project.
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.11.0
environment:
  sdk: ^3.5.3
flutter:
  uses-material-design: true
flutter_launcher_icons:
  adaptive_icon_background: assets/icons/background.png
  adaptive_icon_foreground: assets/icons/icon_android.png
  android: launcher_icon
  image_path_android: assets/icons/icon_android.png
  image_path_ios: assets/icons/icon_ios.png
  ios: true
  min_sdk_android: 16
  remove_alpha_ios: true
name: loop_client
publish_to: none
version: 1.6.2+93
