dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  looplus_core:
    git:
      ref: v1.10.2
      url: https://github.com/certainlyWrong/looplus_core.git
description: A new Flutter project.
dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
environment:
  sdk: ^3.5.3
flutter:
  uses-material-design: true
name: loop_client
publish_to: none
version: 1.10.2+109
