# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# submission_information({
#     add_id_info_uses_idfa: false,
#     content_rights_contains_third_party_content: true,
#     export_compliance_platform: 'ios',
#     export_compliance_uses_encryption: true,  # Se o app usa criptografia
#     export_compliance_is_exempt: true,        # Se for isento
#     export_compliance_compliance_required: false,
#     export_compliance_encryption_updated: false,
#     export_compliance_app_type: "public",
#     export_compliance_contains_third_party_cryptography: true,
#     export_compliance_contains_proprietary_cryptography: false,
#     export_compliance_available_on_french_store: true
# })

# submission_information: {
#     add_id_info_uses_idfa: false,
#     export_compliance_platform: 'ios',  # iOS como plataforma
#     export_compliance_uses_encryption: true,  # Definir como true se o app usar criptografia
#     export_compliance_is_exempt: false,  # Defina como false se não houver isenção automática de conformidade
#     export_compliance_contains_third_party_cryptography: true,  # Se você usa bibliotecas de criptografia de terceiros
#     export_compliance_contains_proprietary_cryptography: false,  # Defina como true se você usa criptografia proprietária
#     export_compliance_compliance_required: true,  # Apple precisará revisar essa conformidade
#     export_compliance_encryption_updated: false,  # Defina como true se a criptografia foi atualizada
#     export_compliance_app_type: 'public',  # Tipo de app (público, por exemplo)
#     export_compliance_available_on_french_store: true  # Se está disponível na loja francesa
#   }

