# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh("git", "clone", "https://github.com/certainlyWrong/loop_keystores.git")
    sh("cp loop_keystores/Clube_Clinica_Tatty_Berno/key.properties ..")
    sh("cp loop_keystores/Clube_Clinica_Tatty_Berno/*.jks ../app/")
    sh("rm", "-rf", "loop_keystores")

    sh("flutter", "build", "aab", "--release") || UI.user_error!("Flutter build failed")

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    sh("git", "clone", "https://github.com/certainlyWrong/loop_keystores.git")
    sh("cp loop_keystores/Loop/key.properties ..")
    sh("cp loop_keystores/Loop/*.jks ../app/")
    sh("rm", "-rf", "loop_keystores")

    sh("flutter", "build", "aab", "--release") || UI.user_error!("Flutter build failed")

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
