name: "Loop Deploy"

on:
  push:
    tags:
      - 'v*.release'

env:
  MATCH_PASSWORD: ${{ vars.MATCH_PASSWORD }}
  MATCH_KEYCHAIN_PASSWORD: ${{ vars.MATCH_KEYCHAIN_PASSWORD }}
  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ vars.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
  FASTLANE_PASSWORD: ${{ vars.FASTLANE_PASSWORD }}

jobs:
  ios_deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup git
      run: |
        git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
      id: flutter

    - name: Setup fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.5"
        bundler-cache: true
        working-directory: ios

    - name: Install fastlane
      run: gem install fastlane

    - name: Install dependencies
      run: flutter pub get

    - name: Set fastlane_cicd
      run: echo "${{ secrets.FASTLANE_IOS_CICD }}" >> ./ios/store.json

    - name: ls ios
      run: ls ios
    
    - name: cat ios/store.json
      run: cat ios/store.json

    - name: Validate JSON
      run: |
        python -c 'import json; json.load(open("./ios/store.json"))' && echo "Valid JSON" || echo "Invalid JSON"


    - name: Download metadata
      # run: cd ios && fastlane deliver download_metadata -f --api_key_path store.json
      run: cd ios && bundle exec fastlane deliver download_metadata -f --api_key_path store.json


    - name: Download screenshots
      run: cd ios && fastlane deliver download_screenshots -f --api_key_path store.json

    # - name: Deploy to App Store
    #   run: cd ios && fastlane release

  # android_deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Setup git
  #     run: |
  #       git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"
    
  #   - name: Setup flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.24.3'
  #       channel: 'stable'
  #       cache: true
  #     id: flutter

  #   - name: Setup fastlane
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: "3.3"
  #       bundler-cache: true
  #       working-directory: ios

  #   - name: Install fastlane
  #     run: gem install fastlane

  #   - name: Setup Java 22
  #     uses: actions/setup-java@v3
  #     with:
  #       distribution: 'temurin'
  #       java-version: '22'

  #   - name: Install dependencies
  #     run: flutter pub get

  #   - name: Set fastlane_cicd
  #     run: echo "${{ vars.FASTLANE_ANDROID_CICD }}" >> ./android/fastlane_cicd.json

  #   - name: ls android
  #     run: ls android

  #   - name: cat android/fastlane_cicd.json
  #     run: cat android/fastlane_cicd.json

  #   - name: Deploy to internal Play Store
  #     run: cd android && fastlane release

