name: "Loop Deploy"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*-release"

env:
  MATCH_PASSWORD: ${{ vars.MATCH_PASSWORD }}
  MATCH_KEYCHAIN_PASSWORD: ${{ vars.MATCH_KEYCHAIN_PASSWORD }}
  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ vars.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

jobs:
  # ios_deploy:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup git
  #       run: |
  #         git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

  #     - uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: latest-stable

  #     - name: Setup flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         cache: true
  #       id: flutter

  #     - name: Setup fastlane
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.3"
  #         bundler-cache: true

  #     - name: Install fastlane
  #       uses: tashi-iu/setup-fastlane@v1

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Clone fastlane_tools
  #       run: git clone https://github.com/certainlyWrong/fastlane_tools.git

  #     - name: Copy store.json
  #       run: cp fastlane_tools/store.json ios/store.json

  #     - name: Copy .env
  #       run: cp fastlane_tools/.env ios/fastlane/.env

  #     - name: Validate JSON
  #       run: |
  #         python -c 'import json; json.load(open("./ios/store.json"))' && echo "Valid JSON" || echo "Invalid JSON"

  #     - name: Download screenshots
  #       run: cd ios && bundle exec fastlane deliver download_metadata -f --api_key_path store.json --use_live_version true

  #     # - name: Download screenshots
  #     #   run: cd ios && bundle exec fastlane deliver download_screenshots -f --api_key_path store.json --use_live_version true

  #     - name: Deploy to App Store
  #       run: cd ios && fastlane release

  android_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"
          channel: "stable"
        id: flutter

      - name: Setup fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install fastlane
        uses: tashi-iu/setup-fastlane@v1

      - name: Setup Java 22
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Install dependencies
        run: flutter pub get

      - name: Clone fastlane_tools
        run: git clone https://github.com/certainlyWrong/fastlane_tools.git

      - name: Copy fastlane_cicd.json
        run: cp fastlane_tools/fastlane_cicd.json android/fastlane_cicd.json

      - name: Deploy to internal Play Store
        run: cd android && fastlane release
