name: "Loop Deploy"
on:
  workflow_dispatch:

jobs:
  ios_deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup git
      run: |
        git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
      id: flutter

    - name: Setup fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
        working-directory: ios

    - name: Install fastlane
      run: gem install fastlane
    
    - name: Fastlane version
      run: fastlane --version

    - name: Install dependencies
      run: flutter pub get

  android_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup git
      run: |
        git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"
    
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
      id: flutter

    - name: Setup fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
        working-directory: ios

    - name: Install fastlane
      run: gem install fastlane

    - name: Setup Java 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Install dependencies
      run: flutter pub get

    - name: Get fastlane_tools
      run: git clone https://github.com/certainlyWrong/fastlane_tools.git

    - name: ls
      run: ls

    - name: Run fastlane_tools
      run: cd fastlane_tools && chmod +x run.sh && ./run.sh

    - name: ls
      run: ls

    - name: Deploy to internal Play Store
      run: cd android && fastlane beta

